auth:
  enable: true
  mysql:
    maxconection: 2
    host: localhost
    database: bbs    
    username: bbs
    password: password
noob:
  enable: true
fun:
  enable: true
signtp:
  enable: true
  mysql:
    maxconection: 2
    host: localhost
    database: minecraft
    username: minecraft
    password: password    
choptree:
  enable: true
mine:
  enable: true
  mysql:
    maxconection: 2
    host: localhost
    database: minecraft
    username: minecraft
    password: password    