auth:
  enable: true
  mysql: auth
noob:
  enable: true
fun:
  enable: true
signtp:
  enable: true
  mysql: minecraft 
choptree:
  enable: true
mine:
  enable: true
  mysql: minecraft 
database:
  mysql:
    auth:
      maxconection: 2
      host: localhost
      database: bbs    
      username: bbs
      password: password
    minecraft:
      maxconection: 2
      host: localhost
      database: minecraft
      username: minecraft
      password: password
  mongodb:
      