name: KimeCraft
main: me.kime.kc.KimeCraft
version: ${project.version}
author: Kime
load: POSTWORLD
commands:
    login:
        description: Login into a account
        aliases: l
        usage: /login password
    city:
        description: go back to city
        usage: /city
    mine:
        description: go to mine world
        usage: /mine
    skull:
    pu:
    pd:
    roll:
      description: roll a number between 1 - 100
      usage: /roll
    kimecraft:
      description: kimecraft plugin commands
      usage: /kimecarft
      aliases: kc
    chat:
        description: chatting channels
        aliases: c
        usage: /chat channel
    party:
        description: create parties
        usage: /party