name: KimeCraft
main: me.kime.kc.KC
version: ${project.version}
author: Kime
load: POSTWORLD
depend: [Vault]
commands:
    login:
        description: Login into a account
        usage: /login password
    city:
        description: go back to city
        usage: /city
    mine:
        description: go to mine world
        usage: /mine
    skull:
    pu:
    pd: